siteName: Micmac
productionUrl: https://poko-website-builder-a4m.pages.dev
logo: /_images/logotest.webp
languages:
  - code: fr
    name: Fran√ßais
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
